email: aw@eddolearning.com
full_name: Matt Anthes-Washburn
name: Matt A-W
background: AW is CEO and co-founder of Eddo Learning. Eddo Learning is a startup building tools for educators teaching OpenSciEd.
schedule_preferences: By default, unless specified otherwise, you should make meetings 30 minutes long.
background_preferences:
response_preferences:
timezone: "PST"
rewrite_preferences:
  - AW's tone is friendly and concise.
triage_no: |
  - Automated emails from services that are spamming
  - Cold outreach from vendors - this happens a lot as people try to sell him things. He is not interested in these
  - Emails where they are asking questions that can best be answered by other people on the thread. \
  AW is often on a lot of threads with people from his company (Eddo Learning) but often times he does not need to chime in. \
  The exception to this is if AW is the main driver of the conversation. \
  You can usually tell this by whether AW was the one who sent the last email
  - Notifications of comments on Google Docs
  - Automated calendar invitations
  - Emails from friends - even these don't ask an explicit question, if it seems like something a good friend would respond to, AW should do so.
  - Emails from potential customers - if it seems like they are referencing an event or a conversation they had before, AW should probably respond.
triage_notify: |
  - Google docs that were shared with him (do NOT notify him on comments, just new shares)
  - Docusign things that needs to sign. These are using from Docusign and start with "Complete with Docusign". \
  Note: if the Docusign is already signed, you do NOT need to notify him. The way to tell is that those emails start \
  with "Completed: Complete with Docusign". Note the "Completed". Do not notify him if "Completed", only if still needs to be completed.
  - Anything that is pretty technically detailed about Eddo Learning. AW sometimes gets asked questions about Eddo Learning, \
  while he may not always respond to those he likes getting notified about them
  - Emails where there is a clear action item from AW based on a previous conversation, like adding people to a slack channel
triage_email: |
  - Emails from clients that explicitly ask AW a question
  - Emails from clients where someone else has scheduled a meeting for AW, and AW has not already chimed in to express his excitement
  - Emails from clients or potential customers where AW is the main driver of the conversation
  - Emails from other Eddo Learning team members that explicitly ask AW a question
  - Emails where AW has gotten added to a thread with a customer and he hasn't yet said hello
  - Email from clients where they are trying to set up a time to meet
  - Emails where Eddo Learning is winning an award/being invited to a legitimate event
  - Emails where it seems like AW has a pre-existing relationship with the sender. If they mention meeting him from before or they have done an event with him before, he should probably respond. If it seems like they are referencing an event or a conversation they had before, AW should probably respond. 
  - Emails from friends - even these don't ask an explicit question, if it seems like something a good friend would respond to, AW should do so.

  Reminder - automated calendar invites do NOT count as real emails
memory: true
